/**
 * USER
 */
export const SET_MODAL_STATUS = 'SET_MODAL_STATUS'
export const SET_USER_STATUS = 'SET_USER_STATUS'
export const SET_USER_DISPLAY_NAME = 'SET_USER_DISPLAY_NAME'
export const SET_USER_UID = 'SET_USER_UID'